### ISSUE TITLE
How to detect SPAM in SMS text

### ISSUE THREAD

**Issue by sujit-baniya** [PaluMacil/ham#1]
Is there any existing library to detect SPAM in SMS Text? I found one library: https://github.com/PaluMacil/ham But can't find how to use it.
I thought the file testMsgs.data was for training and I could pass actual text for detecting SPAM
Any help is appreciable!

**Comment by PaluMacil** [comment]
This application was designed to demonstrate a concept and show its accuracy. It splits the data into training and testing to prove its accuracy and outputs a report on this, but it doesn't have a command to test a spam message. A function that takes a string of a message and returns a true or false would be pretty trivial to add. What is your use case? What requirements do you have for your project? Are you only supporting English?

**Comment by sujit-baniya** [comment]
Thanks for your response! 
Sorry for above COPIED text from Reddit (I questioned on Reddit)
My use case is for identifying SPAM text for SMS.
I was looking for tool that I could provide spam sentences for learning(training).
Then I could use a function to check if actual text is SPAM or not.

I want the project to be able to support most of the languages like Chinese, South Korean, Dutch, French, etc.
At the moment I'm using Google translator to translate other languages to English and check Spam.
 I tried to use this tool: https://github.com/legion-zver/shield for checking SPAM Text.
My code:
```go

type Train struct {
	Class string `csv:"v1"`
	Msg   string `csv:"v2"`
}

func main() {
	var t []*Train
	clientsFile, err := os.OpenFile("spam.csv", os.O_RDWR|os.O_CREATE, os.ModePerm)
	if err != nil {
		panic(err)
	}
	defer clientsFile.Close()
	if err := gocsv.UnmarshalFile(clientsFile, &t); err != nil { // Load clients from file
		panic(err)
	}
	sh := shield.New(
		shield.NewEnglishTokenizer(),
		shield.NewRedisStore("127.0.0.1:6379", "", "0", nil, ""),
	)
	for _, tokens := range t {
		_ = sh.Learn(tokens.Class, tokens.Msg)
	}
	strs := []string{
		"Chase Alert : We need to verify your identity due to suspicious activity Verify your identity within next 24 hr at betichod.com Thank You",
		"Dear Applicant, We would like to inform you that your claim is almost sorted, our solicitors will inform you about the refund value very soon. Confirmation call will be given to you once it has done. If you have any confusion, please give us a call on our helpline number 01980669836",
		"CLIENTE: VisionNET Operacional IDENTIFICACAO: PAY-5551 EVENTO: Botao de S.O.S pressionado DATA: 2020-11-26 11:59:41",
		"Bonjour, MARIE JEANNE P. vos resultats seront accessibles sur www.mlab-groupe.fr Votre identifiant personnel: P-002773847",
		"Здравствуйте. Спасибо, что воспользовались услугами нашей доской объявлений Юла. ofq.me/l/f4b05",
		"Foje funkcias kaj foje ne funkcias",
		"गुल्मी दुर्घटना : मृतक संख्या ६ पुग्यो [अपडेट] त्नपार्क अहिले फेरि विवादमा तानिएको छ",
		"त्नपार्क अहिले फेरि विवादमा तानिएको छ । सञ्चारमाध्यम, सामाजिक सञ्जाल र कतिपय साामाजिक कार्यक्रमहरूमा विरोध घन्किरहेको छ । आफू स्वयंले राष्ट्रिय विभूति शंखधर साख्वःलाई आदर्श व्यक्तित्व मान्दै",
	}
	for _, str := range strs {
		c, _ := sh.Classify(translateToEn(str))
		fmt.Println(c)
	}
}

func translateToEn(text string) string {
	info := whatlanggo.Detect(text)
	if info.Lang.Iso6391() == "en" {
		return text
	}
	params := googletrans.TranslateParams{
		Src:  "auto",
		Dest: language.English.String(),
	}
	params.Text = text
	translatedText, _ := googletrans.Translate(params)
	return translatedText.Text
}
```

**Comment by PaluMacil** [comment]
It sounds like the learning library you found does what you need for the learning part already. For the language conversion, I would anticipate a large accuracy drop for non-English. Someone sending spam in another language isn't necessarily talkign about the same things, same products, and same tricks. If you can find training data in other languages, you'll want to use that. Sadly I only have English available, but the learning libraries should both be about the same if you find the training data.
